name: Docker Image CI

on:
  push:
    branches: [ master ]

env:
  ACR_NAME: cacregistry
  ACR_RG: cacghost
  ACR_REPO: issomysql

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Build and push the Docker image
      run: |
        az acr login -n ${{ env.ACR_NAME }}
        
        fqRepo="${{ env.ACR_NAME }}.azurecr.io/${{ env.ACR_REPO }}"
        fqTag="$fqRepo:1.0.${{ github.run_number }}"
        latestTag="$fqRepo:latest"

        docker build . --file Dockerfile --tag $fqTag
        docker push $fqTag
        docker tag $fqTag $latestTag
        docker push $latestTag
